import { useEffect, useId, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowUpRight, Check, ChevronRight, Copy, Database, LoaderCircle, TriangleAlert, X } from 'lucide-react';
import { chains } from './data/services';
import type { Chain, DataState } from './data/services';

export function Logo({ small = false }: { small?: boolean }) { return <a className={`logo ${small ? 'small' : ''}`} href="#/" aria-label="ATRA home"><svg viewBox="0 0 38 38" aria-hidden="true"><path d="M4 32 18.8 5 34 32H23.5l-4.7-10-4.7 10z" fill="currentColor"/><path d="M16.3 30h5v5h-5z" fill="currentColor"/></svg><span>ATRA<span className="logo-period">.</span></span></a>; }
export function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
export function ChainMark({ chain }: { chain: string }) { return <span className={`chain-mark ${chain === 'Base' ? 'base' : chain === 'Solana' ? 'solana' : chain === 'BNB Smart Chain' ? 'bnb' : 'robinhood'}`} aria-hidden="true">{chain === 'Base' ? '—' : chain === 'Solana' ? '≋' : chain === 'BNB Smart Chain' ? '◇' : '↗'}</span>; }
export function ChainBadge({ chain }: { chain: string }) { return <span className="chain-label"><ChainMark chain={chain}/>{chain}</span>; }
export function Button({ children, onClick, variant = '', disabled = false, type = 'button', className = '' }: { children: ReactNode; onClick?: () => void; variant?: string; disabled?: boolean; type?: 'button' | 'submit'; className?: string }) { return <button type={type} className={`button ${variant} ${className}`} onClick={onClick} disabled={disabled}>{children}</button>; }
export function Panel({ title, eyebrow, action, children, className = '' }: { title?: string; eyebrow?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{title && <div className="panel-head"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h3>{title}</h3></div>{action}</div>}{children}</section>; }
export function Metric({ label, value, note, positive = false }: { label: string; value: string; note?: string; positive?: boolean }) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{note && <small className={positive ? 'positive' : ''}>{positive && <ArrowUpRight size={13}/>} {note}</small>}</div>; }
export function PageHead({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <header className="page-head"><div><div className="eyebrow">WORKSPACE / {title.toUpperCase()}</div><h1>{title}</h1><p>{description}</p></div>{action}</header>; }
export function Warning({ children, danger = false }: { children: ReactNode; danger?: boolean }) { return <div className={`warning ${danger ? 'danger' : ''}`}><TriangleAlert size={17}/><div>{children}</div></div>; }
export function DataNotice({ short = false }: { short?: boolean }) { return <div className="data-notice"><Database size={14}/><span>{short ? 'Illustrative data · Paper mode' : 'Demo workspace — all market values, balances, positions, and activity are simulated. No runtime is connected.'}</span></div>; }
export function EmptyState({ title = 'Nothing here yet', children }: { title?: string; children?: ReactNode }) { return <div className="empty-state"><Database size={26}/><h3>{title}</h3><p>{children || 'New activity will appear here when your local runtime is connected.'}</p></div>; }
export function DataStatus({ state, retry }: { state: DataState; retry?: () => void }) { if (state === 'loading') return <div className="empty-state" role="status"><LoaderCircle className="spinner" size={25}/><h3>Loading market snapshot</h3><p>Preparing the demonstration dataset.</p></div>; if (state === 'error') return <div className="empty-state" role="alert"><TriangleAlert size={25}/><h3>Provider unavailable</h3><p>Market data could not be retrieved. Check your provider connection.</p><Button onClick={retry}>Try again</Button></div>; if (state === 'stale') return <Warning>Stale snapshot. Refresh your provider before considering any action.</Warning>; return null; }
export function CopyButton({ value, label = 'Copy' }: { value: string; label?: string }) { const [status, setStatus] = useState(''); return <button className="copy-button" onClick={async () => { try { await navigator.clipboard.writeText(value); setStatus('Copied'); } catch { setStatus('Copy unavailable'); } }} aria-label={status || label}>{status === 'Copied' ? <Check size={15}/> : <Copy size={15}/>}<span>{status || label}</span></button>; }
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
export function ChainFilter({ value, onChange, all = true }: { value: string; onChange: (value: string) => void; all?: boolean }) { return <select aria-label="Filter by chain" value={value} onChange={e => onChange(e.target.value)}>{all && <option>All chains</option>}{chains.map(c => <option key={c}>{c}</option>)}</select>; }
export function ChainChoices({ value, onChange }: { value: Chain[]; onChange: (value: Chain[]) => void }) { return <div className="chain-choices">{chains.map(c => <label key={c}><ChainBadge chain={c}/><input type="checkbox" checked={value.includes(c)} onChange={e => onChange(e.target.checked ? [...value, c] : value.filter(x => x !== c))}/></label>)}</div>; }
export function Segmented({ items, value, onChange }: { items: string[]; value: string; onChange: (v: string) => void }) { return <div className="segmented">{items.map(i => <button key={i} className={value === i ? 'active' : ''} onClick={() => onChange(i)} aria-pressed={value === i}>{i}</button>)}</div>; }
export function Modal({ title, onClose, children, wide = false }: { title: string; onClose: () => void; children: ReactNode; wide?: boolean }) { const ref = useRef<HTMLDialogElement>(null); const id = useId(); useEffect(() => { const dialog = ref.current; const previous = document.activeElement as HTMLElement | null; dialog?.showModal(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { dialog?.close(); document.body.style.overflow = old; previous?.focus(); }; }, []); return <dialog ref={ref} className={`modal ${wide ? 'wide' : ''}`} aria-labelledby={id} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><header><div><span className="eyebrow">ATRA / LOCAL WORKSPACE</span><h2 id={id}>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></header><div className="modal-body">{children}</div></dialog>; }
export function Sparkline({ values, negative = false }: { values: number[]; negative?: boolean }) { if (!values.length) return <span className="muted">—</span>; return <svg className={`sparkline ${negative ? 'negative' : ''}`} viewBox="0 0 100 36" aria-label="Illustrative price trend" role="img"><polyline points={values.map((v,i)=>`${i * 100/(values.length-1)},${35-v*.32}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>; }
export function PortfolioChart({ range = '1W', compact = false }: { range?: string; compact?: boolean }) { const paths: Record<string, string> = { '1D': '0,125 20,122 35,131 55,115 80,118 95,99 115,109 140,92 165,96 190,70 220,80 245,64 270,75 295,52 320,62 350,39 375,48 400,29 430,38 460,22 490,28 520,17 550,20 580,10', '1W': '0,139 18,142 35,129 52,134 68,112 86,122 100,107 115,114 132,93 149,97 167,83 181,96 199,91 215,70 232,81 247,76 263,88 280,65 296,62 313,74 329,45 345,56 361,42 378,51 394,29 410,37 428,25 445,43 460,34 477,45 493,25 511,32 528,18 547,23 563,13 580,18', '1M': '0,149 30,132 55,142 75,126 100,120 125,133 150,99 175,114 200,93 225,98 250,72 275,85 300,61 325,71 350,54 375,71 400,40 425,52 450,29 475,37 500,13 525,22 550,8 580,17' }; const points = paths[range] || paths['1W']; return <div className={`portfolio-chart ${compact ? 'compact' : ''}`}><div className="chart-y"><span>$12,800</span><span>$12,400</span><span>$12,000</span><span>$11,600</span></div><svg viewBox="0 0 580 170" preserveAspectRatio="none" role="img" aria-label={`Simulated portfolio value over ${range}`}><defs><linearGradient id={compact ? 'chart-fill-small' : 'chart-fill'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#bfed79" stopOpacity=".12"/><stop offset="100%" stopColor="#bfed79" stopOpacity="0"/></linearGradient></defs>{[20,65,110,155].map(y=><line key={y} x1="0" y1={y} x2="580" y2={y} stroke="currentColor" strokeDasharray="3 5"/>)}<polygon points={`0,170 ${points} 580,170`} fill={`url(#${compact ? 'chart-fill-small' : 'chart-fill'})`}/><polyline points={points} stroke="#c4ef82" strokeWidth="2" fill="none" vectorEffect="non-scaling-stroke"/><circle cx="580" cy="18" r="3.5" fill="#c4ef82"/></svg><div className="chart-x">{(range === '1D' ? ['00:00','04:00','08:00','12:00','16:00','20:00','23:59'] : range === '1M' ? ['Jun 01','Jun 05','Jun 10','Jun 15','Jun 20','Jun 25','Jun 30'] : ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']).map(t=><span key={t}>{t}</span>)}</div></div>; }
export function TextLink({ href, children }: { href: string; children: ReactNode }) { return <a className="text-link" href={href}>{children}<ChevronRight size={15}/></a>; }
