import { useEffect, useState } from 'react';
import { ArrowDownUp, ArrowUpRight, Search, Star, X } from 'lucide-react';
import { Badge, Button, ChainBadge, ChainFilter, DataNotice, DataStatus, EmptyState, Field, Panel, Sparkline, Warning, TokenMark } from './components';
import { compactMoney, marketService, money } from './data/services';
import { ageLabel } from './data/live-market';
import type { DataState, Market, Research } from './data/services';

export function MarketExplorer({ local = false, preview = false }: { local?: boolean; preview?: boolean }) {
  const [rows, setRows] = useState<Market[]>([]); const [state, setState] = useState<DataState>('loading'); const [scenario, setScenario] = useState<DataState>('ready');
  const [query, setQuery] = useState(''); const [chain, setChain] = useState('All chains'); const [sort, setSort] = useState('volume'); const [selected, setSelected] = useState<Market | null>(null);
  const [research, setResearch] = useState<Research | null>(null); const [researchLoading, setResearchLoading] = useState(false); const [watchlist, setWatchlist] = useState<string[]>([]); const [watchOnly, setWatchOnly] = useState(false);
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { let active = true; const load = () => marketService.list(scenario).then(data => { if (active) { setRows(data); setState(scenario); setNow(Date.now()); } }).catch(() => { if (active) setState('error'); }); load(); const refresh = scenario === 'ready' ? window.setInterval(load, 60_000) : undefined; const tick = window.setInterval(() => setNow(Date.now()), 10_000); return () => { active = false; if (refresh) window.clearInterval(refresh); window.clearInterval(tick); }; }, [scenario]);
  const live = state === 'ready' && rows.some(r => r.source === 'dexscreener');
  const asOf = rows.reduce<number | null>((latest, r) => (r.observedAt && (latest === null || r.observedAt > latest) ? r.observedAt : latest), null);
  const changeScenario = (v: DataState) => { setState('loading'); setScenario(v); };
  const filtered = rows.filter(r => (chain === 'All chains' || r.chain === chain) && `${r.name} ${r.symbol} ${r.pool}`.toLowerCase().includes(query.toLowerCase()) && (!watchOnly || watchlist.includes(r.id))).sort((a,b) => sort === 'name' ? a.symbol.localeCompare(b.symbol) : (b[sort as 'volume' | 'price' | 'change'] ?? -Infinity) - (a[sort as 'volume' | 'price' | 'change'] ?? -Infinity));
  return <div className="market-explorer">{!preview && <><DataNotice live={live} asOf={asOf === null ? null : ageLabel(asOf, now)}/><div className="market-toolbar"><label className="search-input"><Search size={16}/><input aria-label="Search assets or pairs" placeholder="Search assets or pairs..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></label><ChainFilter value={chain} onChange={setChain}/><label className="sort-select"><ArrowDownUp size={14}/><select aria-label="Sort markets" value={sort} onChange={e=>setSort(e.target.value)}><option value="volume">Volume</option><option value="price">Price</option><option value="change">24h change</option><option value="name">Asset name</option></select></label>{local && <Button variant={watchOnly ? 'selected' : ''} onClick={()=>setWatchOnly(!watchOnly)}><Star size={14}/>Watchlist</Button>}<details className="scenario"><summary>Preview states</summary><select aria-label="Market preview state" value={scenario} onChange={e=>changeScenario(e.target.value as DataState)}>{(['ready','loading','empty','stale','error'] as const).map(s=><option key={s} value={s}>{s === 'error' ? 'Provider unavailable' : s}</option>)}</select></details></div></>}
  <DataStatus state={state} retry={()=>changeScenario('ready')}/>{!['loading','error'].includes(state) && <>{filtered.length ? <div className="table-scroll"><table className="market-table"><thead><tr>{local && <th><span className="sr-only">Watchlist</span></th>}<th>Asset / Pair</th><th>Chain</th><th className="numeric">Price</th><th className="numeric">24h change</th>{preview && <th>7D trend</th>}<th className="numeric">Volume (24h)</th>{!preview && <><th className="numeric">Liquidity</th><th>Pool</th><th>Updated</th></>}<th><span className="sr-only">Details</span></th></tr></thead><tbody>{(preview ? filtered.slice(0,4) : filtered).map(row=><tr key={row.id}>{local && <td><button className={`icon-button ${watchlist.includes(row.id) ? 'starred' : ''}`} aria-label={`${watchlist.includes(row.id) ? 'Remove' : 'Add'} ${row.symbol} ${row.chain} ${watchlist.includes(row.id) ? 'from' : 'to'} watchlist`} onClick={()=>setWatchlist(w=>w.includes(row.id)?w.filter(id=>id!==row.id):[...w,row.id])}><Star size={15} fill={watchlist.includes(row.id)?'currentColor':'none'}/></button></td>}<td><button className="asset-button" onClick={()=>{setSelected(row);setResearch(null);}}><TokenMark symbol={row.symbol}/><span><strong>{row.symbol}</strong><small>{row.name}</small></span></button></td><td><ChainBadge chain={row.chain}/></td><td className="numeric mono">{money(row.price)}</td><td className={`numeric mono ${row.change === null ? '' : row.change >= 0 ? 'positive' : 'negative'}`}>{row.change === null ? '—' : `${row.change >= 0 ? '+' : ''}${row.change.toFixed(2)}%`}</td>{preview && <td>{row.history.length > 0 ? <Sparkline values={row.history} negative={(row.change ?? 0)<0}/> : <span className="muted">—</span>}</td>}<td className="numeric mono">{compactMoney(row.volume)}</td>{!preview && <><td className="numeric mono">{compactMoney(row.liquidity)}</td><td className="muted">{row.pool}</td><td><Badge tone={state==='stale'||row.price===null?'warning-tone':row.source==='dexscreener'?'lime':''}>{row.price===null?'Unavailable':state==='stale'?'Stale':row.source==='dexscreener'?`Live · ${ageLabel(row.observedAt ?? now, now)}`:'Fixture'}</Badge></td></>}<td><button className="icon-button" aria-label={`View ${row.symbol} on ${row.chain}`} onClick={()=>{setSelected(row);setResearch(null);}}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div> : <EmptyState title="No matching markets">Try another search or chain. Watchlisted markets appear after you star an asset.</EmptyState>}</>}
  {selected && <div className="market-detail"><Panel title={`${selected.symbol} / ${selected.chain}`} eyebrow={selected.source === 'dexscreener' ? 'MARKET DETAIL · LIVE DATA' : 'MARKET DETAIL · DEMONSTRATION'} action={<button className="icon-button" aria-label="Close market details" onClick={()=>setSelected(null)}><X size={18}/></button>}><div className="detail-grid"><div><h2>{money(selected.price)}</h2>{selected.history.length > 0 && <Sparkline values={selected.history} negative={(selected.change??0)<0}/>}<dl><dt>Liquidity</dt><dd>{compactMoney(selected.liquidity)}</dd><dt>24h volume</dt><dd>{compactMoney(selected.volume)}</dd><dt>Pool</dt><dd>{selected.pool}</dd><dt>Data source</dt><dd>{selected.source === 'dexscreener' ? 'DexScreener (public API)' : 'Static frontend fixture'}</dd><dt>Freshness</dt><dd>{state==='stale'?'Stale preview':selected.source==='dexscreener'?`Updated ${ageLabel(selected.observedAt ?? now, now)}`:'Not a live snapshot'}</dd><dt>Supported execution</dt><dd>Unavailable · runtime disconnected</dd>{local && <><dt>Agent exposure</dt><dd>No verified exposure</dd><dt>Existing trade / LP</dt><dd>Requires local runtime</dd></>}</dl></div><div><Warning>{selected.price === null ? `Unavailable: ${selected.reason ?? 'this chain has no market provider configured'}.` : selected.source === 'dexscreener' ? 'Live provider data, single source, not cross-checked. Research and execution require a connected local runtime.' : 'Illustrative data only. Connect a provider to research current market conditions.'}</Warning>{local && <><Button disabled={researchLoading || selected.price===null} onClick={async()=>{setResearchLoading(true);try {setResearch(await marketService.research(selected));} finally {setResearchLoading(false);}}}>{researchLoading?'Preparing research...':'Research this market'}<ArrowUpRight size={15}/></Button>{research && <div className="research-report">{[['Observed Data',research.observed],['Agent Interpretation',research.interpretation],['Risks',research.risks],['Missing Data',research.missing],['Suggested Action',research.action]].map(([title,body])=><div key={title}><h4>{title}</h4><p>{body}</p></div>)}</div>}</>}</div></div></Panel></div>}
  {!preview && <div className="table-footer"><span>{filtered.length} markets · Exactly 4 supported chains</span><Field label="Data source"><span>{live ? `DexScreener · live · updated ${asOf === null ? 'just now' : ageLabel(asOf, now)}` : 'Frontend demonstration · fixtures'}</span></Field></div>}
  </div>;
}
